Resources: 
  Ec2Instance: 
    Properties: 
      ImageId: ami-09e67e426f25ce0d7
      KeyName: ansible-key
      SecurityGroups: 
        - InstanceSecurityGroup
    Type: "AWS::EC2::Instance"
  InstanceSecurityGroup: 
    Properties: 
      GroupDescription: "Enable SSH access via port 22"
      SecurityGroupIngress: 
        - 
          CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
    Type: "AWS::EC2::SecurityGroup"
